spring:
  application:
    name: mddback
  profiles:
    active: dev
  docker:
    compose:
      file: ../../docker-compose.yml
      enabled: false
  flyway:
    enabled: true
    url: jdbc:${P6_DB_URL:postgresql://localhost:5432}/dbmdd
    user: ${P6_DB_USER:mdduser}
    driver-class-name: org.postgresql.Driver
    password: ${P6_DB_PASSWORD:mddpw}
    create-schemas: true
    default-schema: mddsocial
    schemas: mddsocial
  r2dbc:
    url: r2dbc:${P6_DB_URL:postgresql://localhost:5432}/dbmdd
    username: ${P6_DB_USER:mdduser}
    password: ${P6_DB_PASSWORD:mddpw}
    properties:
      schema: mddsocial
#  datasource:
#    url: jdbc:postgresql://localhost:5432/dbmdd
#    username: ${P6_DB_USER:mdduser}
#    password: ${P6_DB_PASSWORD:mddpw}
#    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.springframework: DEBUG
    com.mdd.back: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: 'beans'
jwt:
  secret-key: ${P6_JWT_SECRET_KEY:vfUI9b82X2CaSN9clY9o2ijcwkgtoWpbjvyD96iRYUU=}
  expiration-time: ${P6_JWT_EXPIRATION_TIME:3600}
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
frontend:
  url: ${P6_FRONTEND_URL:http://localhost:4200}
